
# Optimization

## Exercise 1
Find a value that satisfies the following formula using cvxpy method

In [1]:
import numpy as np
import cvxpy as cvx

f = np.array([[2], [3]])

lb = np.array([[1], [2]])
ub = np.array([[10], [10]])

x = cvx.Variable((2, 1))

obj = cvx.Minimize(-f.T @ x)
constraints = [lb <= x, x <= ub]

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[9.99999998]
 [9.99999999]]
-49.999999924906


## Exercise 2
Find a value that satisfies the following formula using cvxpy method

In [2]:
f = np.array([[1],
              [2]])
H = np.array([[1 / 2, 0],
              [0, 0]])

A = np.array([[3, 4],
              [2, 4]])
b = np.array([[80],
              [80]])

x = cvx.Variable((2, 1))

obj = cvx.Minimize(cvx.quad_form(x, H) + f.T @ x)
constraints = [A @ x <= b,
               np.array([[12], [12]]) <= np.array([2, 3]) @ x]

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[0.33333333]
 [3.77777778]]
7.944444444444443


## Exercise 3
Find a value that satisfies the following formula using gradient descent method

In [5]:
H = np.matrix([[10, -2], [-2, 10]])
g = -np.matrix([[-4], [-4]])

x = np.zeros((2, 1))
alpha = 0.2

for i in range(25):
    df = H*x + g
    x -= alpha * df

print(x)

[[-0.50000142]
 [-0.50000142]]
