In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn import metrics

### 실습 과제 1. 데이터 불러온 후 NaN 값이 있다면 해당 행 제거하고, train_data : test_data = 7:3 split
#### 종속변수는 PKT_Y, 나머지 변수들이 독립변수

In [26]:
df = pd.read_csv('../data/contest.csv')

In [27]:
df = df.dropna(subset=['PKT_Y'])

In [28]:
X=df.iloc[:,6:86]
y=df['PKT_Y']

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=42)

### 실습 과제 2. 선형 커널, 3차항 커널, RBF 커널, 시그모이드 커널로 각각 SVM 모델 구현 후 accuracy, F1 score, confusion matrix, precision, recall (C=1, gamma = 0.1)

In [30]:
svm_lin = svm.SVC(kernel='linear', C=1, gamma=0.1).fit(X_train,y_train)
y_pred = svm_lin.predict(X_test)
print("linear ============>")
print(f'accuracy : {metrics.accuracy_score(y_test, y_pred)}')
print(f'f1 score : {metrics.f1_score(y_test, y_pred)}')
con_mat = metrics.confusion_matrix(y_test, y_pred)
print(f'confusion matrix : \n{con_mat}')
print('precisoin: ', con_mat[1][1]/(con_mat[1][1]+con_mat[0][1]))
print('recall: ', con_mat[1][1]/(con_mat[1][1]+con_mat[1][0]))

linear ============>
accuracy : 0.6142131979695431
f1 score : 0.5648854961832062
confusion matrix : 
[[215  80]
 [148 148]]
precisoin:  0.6491228070175439
recall:  0.5


In [31]:
svm_poly = svm.SVC(kernel='poly', C=1, gamma=0.1).fit(X_train, y_train)
y_pred = svm_poly.predict(X_test)
print("poly ============>")
print(f'accuracy : {metrics.accuracy_score(y_test, y_pred)}')
print(f'f1 score : {metrics.f1_score(y_test, y_pred)}')
con_mat = metrics.confusion_matrix(y_test, y_pred)
print(f'confusion matrix : \n{con_mat}')
print('precisoin: ', con_mat[1][1] / (con_mat[1][1] + con_mat[0][1]))
print('recall: ', con_mat[1][1] / (con_mat[1][1] + con_mat[1][0]))

poly ============>
accuracy : 0.5956006768189509
f1 score : 0.5678119349005426
confusion matrix : 
[[195 100]
 [139 157]]
precisoin:  0.6108949416342413
recall:  0.5304054054054054


In [32]:
svm_rbf = svm.SVC(kernel='rbf', C=1, gamma=0.1).fit(X_train, y_train)
y_pred = svm_rbf.predict(X_test)
print("rbf ============>")
print(f'accuracy : {metrics.accuracy_score(y_test, y_pred)}')
print(f'f1 score : {metrics.f1_score(y_test, y_pred)}')
con_mat = metrics.confusion_matrix(y_test, y_pred)
print(f'confusion matrix : \n{con_mat}')
print('precisoin: ', con_mat[1][1] / (con_mat[1][1] + con_mat[0][1]))
print('recall: ', con_mat[1][1] / (con_mat[1][1] + con_mat[1][0]))

rbf ============>
accuracy : 0.5549915397631133
f1 score : 0.6362378976486861
confusion matrix : 
[[ 98 197]
 [ 66 230]]
precisoin:  0.5386416861826698
recall:  0.777027027027027


In [33]:
svm_sig = svm.SVC(kernel='sigmoid', C=1, gamma=0.1).fit(X_train, y_train)
y_pred = svm_sig.predict(X_test)
print("sigmoid ============>")
print(f'accuracy : {metrics.accuracy_score(y_test, y_pred)}')
print(f'f1 score : {metrics.f1_score(y_test, y_pred)}')
con_mat = metrics.confusion_matrix(y_test, y_pred)
print(f'confusion matrix : \n{con_mat}')
print('precisoin: ', con_mat[1][1] / (con_mat[1][1] + con_mat[0][1]))
print('recall: ', con_mat[1][1] / (con_mat[1][1] + con_mat[1][0]))

sigmoid ============>
accuracy : 0.38578680203045684
f1 score : 0.3794871794871795
confusion matrix : 
[[117 178]
 [185 111]]
precisoin:  0.38408304498269896
recall:  0.375


### 실습 과제 3. 하이퍼 파라미터 C 값(0.01, 0.1, 1, 10)에 따른 RBF 커널을 SVM 모델의 accuracy와 F1 score 변화 관찰

In [34]:
for C in (0.01, 0.1, 1, 10):
    svm_rbf = svm.SVC(kernel='rbf', C=C, gamma=0.1).fit(X_train, y_train)
    y_pred = svm_rbf.predict(X_test)
    print(f"C = {C} ============>")
    print(f'accuracy : {metrics.accuracy_score(y_test, y_pred)}')
    print(f'f1 score : {metrics.f1_score(y_test, y_pred)}')

C = 0.01 ============>
accuracy : 0.5008460236886633
f1 score : 0.6674182638105975
C = 0.1 ============>
accuracy : 0.5329949238578681
f1 score : 0.655860349127182
C = 1 ============>
accuracy : 0.5549915397631133
f1 score : 0.6362378976486861
C = 10 ============>
accuracy : 0.5431472081218274
f1 score : 0.64


### 실습 과제 4. 하이퍼 파라미터 gamma 값(0.005,0.01,0.1, 1)에 따른 RBF 커널을 SVM 모델의 accuracy와 F1 score 변화 관찰

In [35]:
for gamma in (0.005,0.01,0.1, 1):
    svm_rbf = svm.SVC(kernel='rbf', C=1, gamma=gamma).fit(X_train, y_train)
    y_pred = svm_rbf.predict(X_test)
    print(f"gamma : {gamma} ============>")
    print(f'accuracy : {metrics.accuracy_score(y_test, y_pred)}')
    print(f'f1 score : {metrics.f1_score(y_test, y_pred)}')

gamma : 0.005 ============>
accuracy : 0.6125211505922166
f1 score : 0.5975395430579965
gamma : 0.01 ============>
accuracy : 0.6159052453468697
f1 score : 0.6260296540362439
gamma : 0.1 ============>
accuracy : 0.5549915397631133
f1 score : 0.6362378976486861
gamma : 1 ============>
accuracy : 0.5245346869712352
f1 score : 0.660217654171705


### 실습 과제 5. 하이퍼 파라미터 degree(1,2,3,4,5)에 따른 다항식 커널 SVM 모델 accuracy와 F1 score 변화 관찰

In [ ]:
for degree in (1,2,3,4,5):
    svm_poly = svm.SVC(kernel='poly', C=1, gamma=0.1, degree=degree).fit(X_train, y_train)
    y_pred = svm_poly.predict(X_test)
    print(f"degree = {degree} ============>")
    print(f'accuracy : {metrics.accuracy_score(y_test, y_pred)}')
    print(f'f1 score : {metrics.f1_score(y_test, y_pred)}')

degree = 1 ============>
accuracy : 0.6091370558375635
f1 score : 0.5633270321361059
degree = 2 ============>
accuracy : 0.5905245346869712
f1 score : 0.5567765567765568
degree = 3 ============>
accuracy : 0.5956006768189509
f1 score : 0.5678119349005426
degree = 4 ============>
accuracy : 0.5736040609137056
f1 score : 0.5418181818181819
